site_name: Home

theme:
  name: null
  custom_dir: 'cinder'
  # colorscheme: dracula
nav:
  - Visão geral: visao-geral.md
  - Perfil usuário:
    - Perfil de usuário: ihc/perfil-de-usuario.md
    - Personas: ihc/personas.md
  - Análise de Requisitos:
    - Características da plataforma: ihc/caracteristicas-plataforma.md
    - Princípios e diretrizes do projeto: ihc/principios-diretrizes.md
    - Metas de usabilidade: ihc/metas-usabilidade.md
    - Guia de estilo: ihc/guia-estilo.md
  - Protótipos:
    - Protótipo de baixa-fidelidade: ihc/prototipo-baixa.md
    - Protótipo de alta-fidelidade: ihc/prototipo-alta.md
  - Pré-rastreabilidade:
    - RichPictures: requisitos/rich-pictures.md
    - Plano de gerenciamento de riscos: requisitos/plano-riscos.md
    - Estimativas: requisitos/estimativas.md
  - Requisitos: requisitos/requisitos.md
  - Modelagem:
    - Léxico: requisitos/lexico.md
    - NFR: requisitos/nfr.md
    - Casos de Uso: requisitos/casos-uso.md
    - Diagramas de Casos de Uso: diagramas/diagrama-casos-uso.md
    - Diagrama de Classes: diagramas/diagrama-classes.md
    - Diagrama de Componentes: diagramas/diagrama-componentes.md
    - Diagrama de Pacotes: diagramas/diagrama-pacotes.md
    - Diagrama de Comunicação: diagramas/diagrama-comunicacao.md
    - Diagrama de Atividades: diagramas/diagrama-atividades.md
    - Diagrama de Estado: diagramas/diagrama-estado.md
  - Padrões:
    - Padrões GRASP: desenho/grasp.md
    - Padrões GoF: desenho/gof.md
  - v: template.md
      